### ISSUE TITLE
$eos->pushAction is error

### ISSUE THREAD

**Issue by kilvn** [alienzin/php-eos-rpc-sdk#1]
$eos->pushAction return error:

PHP Notice:  Undefined index: binargs in /home/kilvn/Desktop/work/web/eos-sdk/vendor/manamine/php-eos-rpc-sdk/src/EosRpc.php on line 84
PHP Notice:  Undefined index: required_keys in /home/kilvn/Desktop/work/web/eos-sdk/vendor/manamine/php-eos-rpc-sdk/src/EosRpc.php on line 114
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to BlockMatrix\EosRpc\WalletController::signTransaction() must be of the type array, null given, called in /home/kilvn/Desktop/work/web/eos-sdk/vendor/manamine/php-eos-rpc-sdk/src/EosRpc.php on line 117 and defined in /home/kilvn/Desktop/work/web/eos-sdk/vendor/manamine/php-eos-rpc-sdk/src/WalletController.php:232
Stack trace:
#0 /home/kilvn/Desktop/work/web/eos-sdk/vendor/manamine/php-eos-rpc-sdk/src/EosRpc.php(117): BlockMatrix\EosRpc\WalletController->signTransaction(Array, NULL, 'cf057bbfb726404...')
#1 /home/kilvn/Desktop/work/web/eos-sdk/vendor/manamine/php-eos-rpc-sdk/src/EosRpc.php(165): BlockMatrix\EosRpc\EosRpc->makeTransaction(Array)
#2 /home/kilvn/Desktop/work/web/eos-sdk/vendor/manamine/php-eos-rpc-sdk/src/EosRpc.php(243): BlockMatrix\EosRpc\EosRpc->pushTransaction(Array, true)
#3 /home/kilvn/Desktop/work/web/eos-sdk/index.php(300): BlockMatrix\EosRpc\EosRpc->pushAction('kilvn.coin', 'buyram', Array, Array, true)
#4 /home/kilvn/Desktop/work/web/eos-sdk/index. in /home/kilvn/Desktop/work/web/eos-sdk/vendor/manamine/php-eos-rpc-sdk/src/WalletController.php on line 232

**Comment by alienzin** [comment]
Can you post your code usage?

**Comment by kilvn** [comment]
The problem is solved, JSON to bin transaction, actor needs and payer is one, I wrote a receiver, thank you.

**Comment by kilvn** [comment]
> Can you post your code usage?

The problem is solved, JSON to bin transaction, actor needs and payer is one, I wrote a receiver, thank you.
